#!/bin/sh --

cleanup() {
    if [ "$server" ] && kill -0 "$server" 2>/dev/null; then
        kill "$server"
        wait "$server"
        xorg=$?
    fi

    stty "$stty" 2>/dev/null || stty sane
}

stty=$(stty -g)
tty=$(tty)
tty=${tty#/dev/tty}

cfgdir=${XDG_CONFIG_HOME:-$HOME/.config}/sx
mkdir -p -- "$cfgdir"

trap 'cleanup; exit "${xorg:-0}"' EXIT

for signal in HUP INT QUIT TERM; do
    trap "cleanup; trap - $signal EXIT; kill -s $signal $$" "$signal"
done

trap '
    trap - USR1
    DISPLAY=:$tty "${@:-$cfgdir/sxrc}"
    kill "$server"
' USR1

(trap '' USR1
 exec Xorg :"$tty" vt"$tty" -keeptty -noreset -nolisten tcp) &
server=$!

wait "$server"
xorg=$?
